<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>
        系统错误
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            错误页面
        </small>
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="error-container">
            <div class="well">
                <h1 class="grey lighter smaller"><span class="blue bigger-125"><i class="ace-icon fa fa-random"></i>500</span>发生了一些错误</h1>
                <hr />
                <h3 class="lighter smaller">但我们正在努力<i class="ace-icon fa fa-wrench icon-animated-wrench bigger-125"></i>它!</h3>
                <div class="space"></div>
                <div>
                    <h4 class="lighter smaller">具体错误信息如下: </h4>
                    <ul class="list-unstyled spaced inline bigger-110 margin-15">
                        <li><i class="ace-icon fa fa-hand-o-right blue"></i><?= $message ?? ''?></li>
                    </ul>
                </div>
                <hr />
                <div class="space"></div>
                <div class="center">
                    <a href="javascript:history.back()" class="btn btn-grey">
                        <i class="ace-icon fa fa-arrow-left"></i>
                        Go Back
                    </a>
                    <a href="/" class="btn btn-primary">
                        <i class="ace-icon fa fa-tachometer"></i>
                        Dashboard
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>