<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>
        用户管理
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            用户列表
        </small>
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-header widget-header-small">
                <h5 class="lighter">搜索</h5>
            </div>
            <div class="widget-body">
                <div class="widget-main">
                    <form class="form-horizontal" method="get" action="">
                        <div class="row-fluid">
                            <label style="display: inline-block;vertical-align: top;margin-right: 10px;">
                                <input type="text" name="keyword" value="<?= $conditions['keyword'] ?? '' ?>" placeholder="ID/用户名"/>
                            </label>
                            <label style="float: right;">
                                <button type="submit" class="btn btn-inverse btn-small">
                                    <i class="fa fa-search"></i>
                                    搜索
                                </button>
                            </label>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table id="simple-table" class="table  table-bordered table-hover">
                    <thead>
                    <tr>
                        <th style="width: 50px" class="center col-sm-1">
                            <label class="pos-rel">
                                <input type="checkbox" class="ace">
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th class="center" style="width: 60px">用户ID</th>
                        <th class="center">用户名</th>
                        <th class="center">用户邮箱</th>
                        <th class="center">创建时间</th>
                        <th class="center">状态</th>
                        <th class="center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($items ?? [] as $k=>$item):?>
                        <tr class="center">
                            <td>
                                <label class="pos-rel">
                                    <input type="checkbox" name="id" value="<?= $item['id']?>" data-status="<?= $item['status']?>" class="ace"/>
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td><?=$item['id']?></td>
                            <td><?=$item['username']?></td>
                            <td><?=$item['email']?></td>
                            <td><?=$item['created_at']?></td>
                            <td class="hidden-480 center">
                                <label>
                                    <input  name="status" onclick="statusChange(<?=$item['id']?>, <?= $item['status'] ? 0 : -1?>)"  <?= $item['status'] ? '' : 'checked'; ?> class="ace ace-switch ace-switch-5" type="checkbox">
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td>
                                <div class="hidden-sm hidden-xs btn-group">
                                    <button class="btn btn-xs btn-info edit" data-p='<?=json_encode($item, JSON_NUMERIC_CHECK|JSON_UNESCAPED_UNICODE)?>'>
                                        <i class="ace-icon fa fa-edit bigger-120"></i>
                                        编辑
                                    </button>
                                </div>
                                <div class="hidden-sm hidden-xs btn-group">
                                    <button class="btn btn-xs btn-pink vlogin" data-p="<?=$item['id']?>">
                                        <i class="ace-icon fa fa-laptop bigger-120"></i>
                                        伪登陆
                                    </button>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer no-margin-top">
            <button class="btn btn-sm btn-info pull-left add" data-dismiss="modal">
                <i class="ace-icon fa fa-plus"></i>
                添加用户
            </button>
            <ul class="pagination pull-right no-margin">
                <?=$page ?? "";?>
            </ul>
        </div>
        <div class="hr hr-18 dotted hr-double"></div>
    </div>
</div>
<div class="col-lg-6">
    <div id="userModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade text-left">
        <div role="document" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="exampleModalLabel" class="modal-title"></h4>
                </div>
                <div class="modal-body row">
                    <div class="form-horizontal">
                        <input type="hidden" id="id" name="id" value="" />
                        <div class="row-fluid">
                            <label class="col-sm-3 control-label no-padding-right" style="margin-top:10px;"> 用户名: </label>
                            <div class="col-sm-9">
                                <input type="text" id="username" name="username" class="col-sm-6" style="margin-top:10px; margin-left:12px;" value="" />
                            </div>
                        </div>
                        <div class="row-fluid">
                            <label class="col-sm-3 control-label no-padding-right" style="margin-top:10px;"> 密码: </label>
                            <div class="col-sm-9">
                                <input type="text" id="password" name="password" class="col-sm-6" style="margin-top:10px; margin-left:12px;" value="" />
                            </div>
                        </div>
                        <div class="row-fluid">
                            <label class="col-sm-3 control-label no-padding-right" style="margin-top:10px;"> 邮箱: </label>
                            <div class="col-sm-9">
                                <input type="text" id="email" name="email" class="col-sm-6" style="margin-top:10px; margin-left:12px;" value="" />
                            </div>
                        </div>
                        <div class="row-fluid">
                            <label class="col-sm-3 control-label no-padding-right" style="margin-top:10px;"> 管理员: </label>
                            <div class="checkbox col-sm-9">
                                <label style="margin-top:10px;">
                                    <input id="is_admin" name="is_admin" type="checkbox" class="ace">
                                    <span class="lbl"> 勾选为管理员</span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-secondary">关闭</button>
                    <button type="button" class="btn btn-info" onclick="add();">保存</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('table th input:checkbox').on('click', function () {
        let that = this;
        $(this).closest('table').find('tr > td:first-child input:checkbox').each(function () {
            this.checked = that.checked;
            $(this).closest('tr').toggleClass('selected');
        });
    });
    $(".edit").on("click", function(){
        clearModal($('.modal-body'));
        let data = $.parseJSON($(this).attr('data-p'));
        $("#id").val(data.id);
        $("#username").val(data.username);
        $("#email").val(data.email);
        if(data.is_admin){
            $("#is_admin").prop('checked', true);
        }
        $(".modal-title").html('编辑用户（密码重新输入即重置密码）');
        $("#userModal").modal("show");
    });
    $(".add").on("click", function(){
        clearModal($('.modal-body'));
        $(".modal-title").html('添加用户');
        $("#userModal").modal("show");
    });

    function add() {
        let id = $("#id").val();
        let username = $("#username").val();
        let password = $("#password").val();
        let is_admin = 0;
        if($("#is_admin").prop('checked')){
            is_admin = 1;
        }
        let email = $("#email").val();
        $("#userModal").modal("hide");
        $.post('/user/add', {id:id, username:username, password:password, email:email, is_admin:is_admin}, function(res){
            if(res.code !== 0){
                layer.msg(res.message, {time:3000});
            }else{
                layer.msg(res.message, {time:2000, end:function (){location.reload();}});
            }
        });
    }

    function statusChange(id, status){
        $.post('/user/save', {id:id, status:status}, function(){});
    }
    $(".vlogin").on("click", function(){
        window.location.href = "/user/vlogin?id=" + $(this).attr('data-p');
    });
</script>