<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>快侠镜像站群管理系统</title>
    <meta name="description" content="非凡站群管理系统" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <link rel="shortcut icon" href="/alocal/assets/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/alocal/assets/css/bootstrap.css" />
    <link rel="stylesheet" href="/alocal/components/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="/alocal/assets/css/ace-fonts.css" />
    <link rel="stylesheet" href="/alocal/assets/css/ace.css" class="ace-main-stylesheet" id="main-ace-style" />
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="/alocal/assets/css/ace-part2.css" class="ace-main-stylesheet" />
    <![endif]-->
    <link rel="stylesheet" href="/alocal/assets/css/ace-skins.css" />
    <link rel="stylesheet" href="/alocal/assets/css/ace-rtl.css" />
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="/alocal/assets/css/ace-ie.css" />
    <![endif]-->
    <!--[if !IE]> -->
    <script src="/alocal/components/jquery/dist/jquery.js"></script>
    <!-- <![endif]-->
    <!--[if IE]>
    <script src="/alocal/components/jquery.1x/dist/jquery.js"></script>
    <![endif]-->
    <script src="/alocal/assets/js/ace-extra.js"></script>
    <!--[if lte IE 8]>
    <script src="/alocal/components/html5shiv/dist/html5shiv.min.js"></script>
    <script src="/alocal/components/respond/dest/respond.min.js"></script>
    <![endif]-->
</head>
<body class="no-skin">
<div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-header pull-left">
            <a href="/" class="navbar-brand">
                <small>
                    <img style="width:25px;margin-top: -5px" src="/alocal/assets/images/logo.png">
                    <b style="color: #cddc39;text-align: center">快侠镜像站群</b> 管理系统
                </small>
            </a>
        </div>
        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <!-- #section:basics/navbar.user_menu -->
                <li class="light-blue dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="/alocal/assets/avatars/user_1.jpeg" alt="Jason's Photo" />
                        <span class="user-info">
                            <small><?echo ucfirst($session['user']['username'] ?? '') ?></small>
                        </span>
                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>
                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li><a href="/"><i class="ace-icon fa fa-cog"></i>Settings</a></li>
                        <li><a href="/"><i class="ace-icon fa fa-user"></i>Profile</a></li>
                        <li class="divider"></li>
                        <li><a href="/login/logout"><i class="ace-icon fa fa-power-off"></i>Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- /section:basics/navbar.layout -->
<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try{ace.settings.loadState('main-container')}catch(e){}
    </script>

    <!-- #section:basics/sidebar -->
    <div id="sidebar" class="sidebar responsive ace-save-state">
        <script type="text/javascript">
            try{ace.settings.loadState('sidebar')}catch(e){}
        </script>
        <ul class="nav nav-list">
            <?php foreach ($session['menus']??[] as $menu):?>
                <?php if($menu['name'] == '用户管理' && empty($session['user']['is_admin'])) break?>
                <?php if($menu['uri'] == '/'):?>
                    <li class="active">
                <?php else:?>
                    <li class="">
                <?php endif;?>
                <a href="<?= !empty($menu['uri']) ? $menu['uri'] : '#'?>" <?= !empty($menu['child']) ? 'class="dropdown-toggle"':''?>>
                    <i class="menu-icon fa <?=$menu['icon']?>"></i>
                    <span class="menu-text"> <?=$menu['name']?> </span>
                    <b class="arrow<?= !empty($menu['child']) ? ' fa fa-angle-down' : ''?>"></b>
                </a>
                <?php if(!empty($menu['child'])):?>
                    <ul class="submenu">
                        <?php foreach ($menu['child'] as $child):?>
                            <li class="">
                                <a href="<?=$child['uri']?>">
                                    <i class="menu-icon fa fa-caret-right"></i>
                                    <?=$child['name']?>
                                </a>
                                <b class="arrow"></b>
                            </li>
                        <?php endforeach;?>
                    </ul>
                <?php endif;?>
                </li>
            <?php endforeach;?>
        </ul>
        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="/">首页</a>
                    </li>
                </ul>
            </div>
            <div class="page-content">
                <div class="ace-settings-container" id="ace-settings-container">
                    <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                        <i class="ace-icon fa fa-cog bigger-130"></i>
                    </div>
                    <div class="ace-settings-box clearfix" id="ace-settings-box">
                        <div class="pull-left width-50">
                            <div class="ace-settings-item">
                                <div class="pull-left">
                                    <select id="skin-colorpicker" class="hide">
                                        <option data-skin="no-skin" value="#438EB9">#438EB9</option>
                                        <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                                        <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                                        <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                                    </select>
                                </div>
                                <span>&nbsp; Choose Skin</span>
                            </div>
                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state" id="ace-settings-add-container" autocomplete="off" />
                                <label class="lbl" for="ace-settings-add-container">
                                    Inside
                                    <b>.container</b>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <?= $content ?? ""?>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="footer-inner">
            <!-- #section:basics/footer -->
            <div class="footer-content">
                <span class="bigger-120">
                    <span class="blue bolder">KuaiXia</span>
                    Application &copy; 2019-2021
                </span>
            </div>
        </div>
    </div>
    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div>
<script type="text/javascript">
    $('#sidebar li').map(function(){
        $(this).removeClass('active');
        $(this).parent().parent().removeClass('open');
    });
    $('#sidebar li a').map(function(){
        let path = window.location.pathname;
        if(path === '/target/edit'){
            path = '/target/index'
        }
        if(path === $(this).attr("href")){
            $(this).parent().addClass('active');
            if($(this).parent().parent().attr('class') === 'submenu'){
                $(this).parent().parent().parent().addClass('open');
            }
        }
    });
    function clearModal(form) {
        $(':input', form).each(function () {
            let type = this.type;
            let tag = this.tagName.toLowerCase();
            if (type === 'text' || type === 'password' || tag === 'textarea')
                this.value = "";
            else if (type === 'checkbox')
                $(this).prop('checked', false);
        });
    }
</script>
<script type="text/javascript">
    if('ontouchstart' in document.documentElement) document.write("<script src='/alocal/components/_mod/jquery.mobile.custom/jquery.mobile.custom.js'>"+"<"+"/script>");
</script>
<script src="/alocal/components/bootstrap/dist/js/bootstrap.js"></script>
<!--[if lte IE 8]>
<script src="/alocal/components/ExplorerCanvas/excanvas.js"></script>
<![endif]-->
<script src="/alocal/components/_mod/jquery-ui.custom/jquery-ui.custom.js"></script>
<script src="/alocal/components/jqueryui-touch-punch/jquery.ui.touch-punch.js"></script>
<script src="/alocal/components/_mod/easypiechart/jquery.easypiechart.js"></script>
<script src="/alocal/components/jquery.sparkline/index.js"></script>
<script src="/alocal/components/Flot/jquery.flot.js"></script>
<script src="/alocal/components/Flot/jquery.flot.pie.js"></script>
<script src="/alocal/components/Flot/jquery.flot.resize.js"></script>
<script src="/alocal/components/layer/layer.js"></script>
<script src="/alocal/components/base64/Base64.js"></script>


<!-- ace scripts -->
<script src="/alocal/assets/js/src/elements.scroller.js"></script>
<script src="/alocal/assets/js/src/elements.colorpicker.js"></script>
<script src="/alocal/assets/js/src/elements.fileinput.js"></script>
<script src="/alocal/assets/js/src/elements.typeahead.js"></script>
<script src="/alocal/assets/js/src/elements.wysiwyg.js"></script>
<script src="/alocal/assets/js/src/elements.spinner.js"></script>
<script src="/alocal/assets/js/src/elements.treeview.js"></script>
<script src="/alocal/assets/js/src/elements.wizard.js"></script>
<script src="/alocal/assets/js/src/elements.aside.js"></script>
<script src="/alocal/assets/js/src/ace.js"></script>
<script src="/alocal/assets/js/src/ace.basics.js"></script>
<script src="/alocal/assets/js/src/ace.scrolltop.js"></script>
<script src="/alocal/assets/js/src/ace.ajax-content.js"></script>
<script src="/alocal/assets/js/src/ace.touch-drag.js"></script>
<script src="/alocal/assets/js/src/ace.sidebar.js"></script>
<script src="/alocal/assets/js/src/ace.sidebar-scroll-1.js"></script>
<script src="/alocal/assets/js/src/ace.submenu-hover.js"></script>
<script src="/alocal/assets/js/src/ace.widget-box.js"></script>
<script src="/alocal/assets/js/src/ace.settings.js"></script>
<script src="/alocal/assets/js/src/ace.settings-rtl.js"></script>
<script src="/alocal/assets/js/src/ace.settings-skin.js"></script>
<script src="/alocal/assets/js/src/ace.widget-on-reload.js"></script>
<script src="/alocal/assets/js/src/ace.searchbox-autocomplete.js"></script>
<link rel="stylesheet" href="/alocal/assets/css/ace.onpage-help.css" />
<link rel="stylesheet" href="/alocal/docs/assets/js/themes/sunburst.css" />
<script type="text/javascript"> ace.vars['base'] = '..'; </script>
<script src="/alocal/assets/js/src/elements.onpage-help.js"></script>
<script src="/alocal/assets/js/src/ace.onpage-help.js"></script>
<script src="/alocal/docs/assets/js/rainbow.js"></script>
<script src="/alocal/docs/assets/js/language/generic.js"></script>
<script src="/alocal/docs/assets/js/language/html.js"></script>
<script src="/alocal/docs/assets/js/language/css.js"></script>
<script src="/alocal/docs/assets/js/language/javascript.js"></script>
</body>
</html>