<div class="page-header">
    <h1>
        全局配置
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            蜘蛛配置
        </small>
    </h1>
</div>
<div class="row">
    <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">
            <i class="ace-icon fa fa-times"></i>
        </button>
        <i class="ace-icon fa fa-check green"></i>
        友情提示：系统检测蜘蛛IP时将匹配如下配置IP，非法IP系统会阻止访问。添加时注意<b class="red"> 蜘蛛IP，一行一个，后两位支持匹配</b>
    </div>
    <div class="col-xs-12">
        <form class="form-horizontal" method="post" action="">
            <input name="id" type="hidden" class="ace"   value="<?= $item['id'] ?? ''?>" />
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right"> 百度蜘蛛IP </label>
                <div class="col-sm-9">
                    <textarea rows="8" type="text" name="baiduspider" class="col-sm-6" placeholder="百度蜘蛛IP，一行一个，后两位支持匹配"><?=$item['baiduspider'] ?? ''?></textarea>
                </div>
            </div><div class="space-4"></div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right"> 谷歌蜘蛛IP </label>
                <div class="col-sm-9">
                    <textarea rows="8" type="text" name="googlebot" class="col-sm-6" placeholder="谷歌蜘蛛IP，一行一个，后两位支持匹配"><?=$item['googlebot'] ?? ''?></textarea>
                </div>
            </div><div class="space-4"></div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right"> 搜狗蜘蛛IP </label>
                <div class="col-sm-9">
                    <textarea rows="8" type="text" name="sogou" class="col-sm-6" placeholder="搜狗蜘蛛IP，一行一个，后两位支持匹配"><?=$item['sogou'] ?? ''?></textarea>
                </div>
            </div><div class="space-4"></div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right"> 神马蜘蛛IP </label>
                <div class="col-sm-9">
                    <textarea rows="8" type="text" name="yisou" class="col-sm-6" placeholder="神马蜘蛛IP，一行一个，后两位支持匹配"><?=$item['yisou'] ?? ''?></textarea>
                </div>
            </div><div class="space-4"></div>
            <div class="clearfix form-actions">
                <div class="col-md-offset-3 col-md-9">
                    <button class="btn" type="reset">
                        <i class="ace-icon fa fa-undo bigger-110"></i>
                        重置
                    </button>
                    <button class="btn btn-info commit" type="button">
                        <i class="ace-icon fa fa-check bigger-110"></i>
                        提交
                    </button>
                </div>
            </div>
        </form>
        <div class="hr hr-18 dotted hr-double"></div>
    </div>
</div>
<script>
    $(".commit").on("click", function(){
        let data = {};
        data.id =  $('input[name="id"]').val();
        data.baiduspider =  $('textarea[name="baiduspider"]').val();
        data.googlebot = $('textarea[name="googlebot"]').val();
        data.sogou =  $('textarea[name="sogou"]').val();
        data.yisou =  $('textarea[name="yisou"]').val();
        $.ajax({
            type: 'POST',
            url: '/config/spider',
            data: data,
            dataType: 'json',
            success: function(res){
                if(res.code !== 0){
                    layer.msg(res.message, {time:3000});
                }else{
                    layer.msg(res.message, {time:1000, end:function (){location.reload();}});
                }
            }
        });
    });
</script>