<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h1>
        站点管理
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            站点映射
        </small>
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">
                <i class="ace-icon fa fa-times"></i>
            </button>
            <i class="ace-icon fa fa-check green"></i>
            友情提示：映射将会
            <strong class="red">
                删除首页缓存
            </strong>， 访问或批量打开站点将会
            <strong class="red">
                创建首页缓存
            </strong>（生成新的TDK，链轮，小指数词）
        </div>
        <div class="widget-box">
            <div class="widget-header widget-header-small">
                <h5 class="lighter">搜索</h5>
            </div>
            <div class="widget-body">
                <div class="widget-main">
                    <form class="form-horizontal" method="get" action="">
                        <div class="row-fluid">
                            <label style="display: inline-block;vertical-align: top;margin-right: 10px;">
                                <input type="text" name="keyword" value="<?= $conditions['keyword'] ?? '' ?>" placeholder="站点ID/域名" />
                            </label>
                            <label style="display: inline-block;vertical-align: top;margin-right: 10px;">
                                <input style="width: 250px" type="text" name="url" value="<?= $conditions['url'] ?? '' ?>" placeholder="目标站地址" />
                            </label>
                            <label class="pos-rel" style="margin-top: 7px">
                                <input type="checkbox" name="wait_mapping" <?php echo !empty($conditions['wait_mapping']) ? 'checked' : '' ?> class="ace">
                                <span class="lbl"> 待映射站点</span>
                            </label>
                            <label style="float: right;">
                                <button type="submit" class="btn btn-inverse btn-small">
                                    <i class="fa fa-search"></i>
                                    搜索
                                </button>
                            </label>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table id="simple-table" class="table  table-bordered table-hover">
                    <thead>
                    <tr>
                        <th style="width: 50px" class="center col-sm-1">
                            <label class="pos-rel">
                                <input type="checkbox" class="ace">
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th class="center" style="width: 60px">站点ID</th>
                        <th class="center">站点域名</th>
                        <th class="center">站点标题</th>
                        <th class="center">目标站地址</th>
                        <th class="center">目标站编码</th>
                        <th class="center">映射时间</th>
                        <th class="center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($items ?? [] as $k=>$item):?>
                        <tr class="center">
                            <td>
                                <label class="pos-rel">
                                    <input type="checkbox" name="id" value="<?= $item['id']?>" data-url="http://<?= $item['domain']?>" data-status="<?= $item['status']?>" class="ace"/>
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td><?=$item['id']?></td>
                            <td><a href="http://<?=$item['domain']?>" target="_blank"><?=$item['domain']?></a></td>
                            <td><span class="keyword_instructions" data-keyword="<?=$item['keyword']?>"><?=mb_strlen($item['keyword']) > 10 ? mb_substr($item['keyword'], 0, 10) . '...' : $item['keyword'] ?></span></td>
                            <td><a href="<?=$item['url']?>" class="url_instructions" data-url="<?=$item['url']?>" target="_blank"><?=mb_strlen($item['url']) > 25 ? mb_substr($item['url'], 0, 25) . '...' : $item['url'] ?></a></td>
                            <td><?=$item['encoding']?></td>
                            <td><?=$item['mapping_at']?></td>
                            <td>
                                <div class="hidden-sm hidden-xs btn-group">
                                    <button class="btn btn-xs btn-primary edit" data-id="<?=$item['id']?>" data-domain="<?=$item['domain']?>">
                                        <i class="ace-icon fa fa-edit bigger-120"></i>
                                        编辑
                                    </button>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer no-margin-top">
            <button class="btn btn-sm btn-primary pull-left batchMapping" data-dismiss="modal">
                <i class="ace-icon fa fa-exchange"></i>
                批量映射
            </button>
            <button class="btn btn-sm btn-success pull-left open" data-dismiss="modal">
                <i class="ace-icon fa fa-share"></i>
                批量打开
            </button>
            <ul class="pagination pull-right no-margin">
                <?=$page ?? "";?>
            </ul>
        </div>
        <div class="hr hr-18 dotted hr-double"></div>
    </div>
</div>
<div class="col-lg-6">
    <div id="siteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade text-left">
        <div role="document" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="exampleModalLabel" class="modal-title">添加站点</h4>
                </div>
                <div class="modal-body row">

                    <div class="form-horizontal">
                        <input type="hidden" id="id" name="id" value="" />
                        <div class="row-fluid">
                            <label class="col-sm-3 control-label no-padding-right" style="margin-top:10px;"> 目标站地址: </label>
                            <div class="col-sm-9">
                                <input type="text" id="url" name="url" class="col-sm-6" style="margin-top:10px; margin-left:12px;" value="" />
                            </div>
                        </div>
                    </div>
                    <div class="form-horizontal">
                        <div class="row-fluid">
                            <label class="col-sm-2 control-label no-padding-right"></label>
                            <div class="col-sm-10">
                                <label style="color: red;margin-top:10px; margin-left:12px;">  注意：目标站地址必须携带协议（https:// 或 http://） </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-secondary">关闭</button>
                    <button type="button" class="btn btn-info" onclick="add();">保存</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    let tips = 0;
    $('.keyword_instructions').mouseenter(function (){
        tips = layer.tips($(this).attr('data-keyword'), $(this), {time:0});
    }).mouseout(function (){
        layer.close(tips);
    });
    $('.url_instructions').mouseenter(function (){
        tips = layer.tips($(this).attr('data-url'), $(this), {time:0});
    }).mouseout(function (){
        layer.close(tips);
    });
    $('table th input:checkbox').on('click', function () {
        let that = this;
        $(this).closest('table').find('tr > td:first-child input:checkbox').each(function () {
            this.checked = that.checked;
            $(this).closest('tr').toggleClass('selected');
        });
    });
    $(".edit").on("click", function(){
        clearModal($('.modal-body'));
        $("#id").val($(this).attr('data-id'));
        $("#domain").val($(this).attr('data-domain'));
        $(".modal-title").html('编辑目标站点');
        $("#siteModal").modal("show");
    });
    $('.open').on('click', function(){
        let urls = $("input:checkbox[name='id']:checked").map(function (index, ele) {
            return $(ele).attr('data-url');
        });
        if (!urls.length) {
            layer.msg("请选择需要操作的站点");
            return false;
        }
        for(let i=0;i< urls.length;i++ ){
            window.open(urls[i]);
        }
    });
    $(".batchMapping").on("click", function(){
        let ids = $("input:checkbox[name='id']:checked").map(function (index, ele) {
            return $(ele).val();
        }).get().join(",");
        let msg;
        if(!ids){
            msg = "你确认重置所有站点的映射关系吗？";
            ids = '0';
        }else{
            let lid = ids.split(',').length;
            msg = "你确认重置 " + lid + " 个站点的映射关系吗？"
        }
        layer.confirm(msg, {icon: 3, title:'提示', btn:['确认','取消']}, function (){
            $.post('/sites/map', {id:ids}, function(res){
                if(res.code !== 0){
                    layer.msg(res.message, {time:3000});
                }else{
                    layer.msg(res.message, {time:1000, end:function (){location.reload();}});
                }
            });
        })
    });
    function add(){
        let id = $("#id").val();
        let url = $("#url").val();
        if(!url){
            layer.msg('目标站地址不能为空');
            return false;
        }
        $("#clearModal").modal("hide");
        $.post('/sites/map', {id:id,url:url}, function(res){
            if(res.code !== 0){
                layer.msg(res.message, {time:3000});
            }else{
                layer.msg(res.message, {time:1000, end:function (){location.reload();}});
            }
        });
    }
</script>