<div class="page-header">
    <h1>
        数据管理
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            标题列表
        </small>
    </h1>
</div>
<div class="row">
    <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">
            <i class="ace-icon fa fa-times"></i>
        </button>
        <i class="ace-icon fa fa-check green"></i>
        友情提示：导入站点数据文件时文本
        <strong class="red">
            内容一行一个
        </strong>
        ，只能是
        <strong class="red">
            txt
        </strong>后缀文本
    </div>
    <div class="col-xs-12">
        <div class="widget-box">
            <div class="widget-header widget-header-small">
                <h5 class="lighter">搜索</h5>
            </div>
            <div class="widget-body">
                <div class="widget-main">
                    <form class="form-horizontal" method="get" action="">
                        <div class="row-fluid">
                            <label style="display: inline-block;vertical-align: top;margin-right: 10px;">
                                <input type="text" name="keyword" value="<?= $conditions['keyword'] ?? '' ?>" placeholder="ID/关键词"/>
                            </label>
                            <label style="display: inline-block;vertical-align: top;margin-right: 10px;">
                                <select name="cate" class="form-control" style="width: 150px">
                                    <option value="">所有类型</option>
                                    <?php foreach (\App\Models\Dao\SitesSource::$source_type_mapping as $k=> $v):?>
                                        <option value="<?=$k?>"  <?= !empty($conditions['cate']) && $conditions['cate'] == $k ? "selected" : ""?> ><?=$v?></option>
                                    <?php endforeach;?>
                                </select>
                            </label>
                            <label style="float: right;">
                                <button type="submit" class="btn btn-inverse btn-small">
                                    <i class="fa fa-search"></i>
                                    搜索
                                </button>
                            </label>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table id="simple-table" class="table  table-bordered table-hover">
                    <thead>
                    <tr>
                        <th class="center" style="width: 50px" class="center col-sm-1">
                            <label class="pos-rel">
                                <input type="checkbox" class="ace">
                                <span class="lbl"></span>
                            </label>
                        </th>
                        <th class="center">ID</th>
                        <th class="center">类型</th>
                        <th class="center">值</th>
                        <th class="center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($items ?? [] as $k=>$item):?>
                        <tr class="center">
                            <td>
                                <label class="pos-rel">
                                    <input type="checkbox" name="id" value="<?= $item['id']?>" data-status="<?= $item['status']?>" class="ace"/>
                                    <span class="lbl"></span>
                                </label>
                            </td>
                            <td><?=$item['id']?></td>
                            <td><?=\App\Models\Dao\SitesSource::$source_type_mapping[$item['cate']]?></td>
                            <td><?=mb_strlen($item['value'])>120 ? mb_substr($item['value'], 0, 120) . '...' : $item['value']?></td>
                            <td>
                                <div class="hidden-sm hidden-xs btn-group">
                                    <button  class="btn btn-xs btn-info edit" data-id="<?=$item['id']?>"  data-cate="<?=$item['cate']?>" data-value="<?=$item['value']?>">
                                        <i class="ace-icon fa fa-edit bigger-120"></i>
                                        编辑
                                    </button>
                                </div>
                                <div class="hidden-sm hidden-xs btn-group">
                                    <button class="btn btn-xs btn-danger delete" data-id="<?=$item['id']?>" data-title="<?=$item['value']?>" >
                                        <i class="ace-icon fa fa-trash bigger-120"></i>
                                        删除
                                    </button>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer no-margin-top">
            <button class="btn btn-sm btn-success pull-left add">
                <i class="ace-icon fa fa-plus"></i>
                添加
            </button>
            <button class="btn btn-sm btn-info pull-left upload">
                <i class="ace-icon fa fa-upload"></i>
                导入
            </button>
            <button class="btn btn-sm btn-danger pull-left batchDelete" data-dismiss="modal">
                <i class="ace-icon fa fa-trash"></i>
                删除
            </button>
            <ul class="pagination pull-right no-margin">
                <?=$page ?? "";?>
            </ul>
        </div>
        <div class="hr hr-18 dotted hr-double"></div>
    </div>
</div>
<input type="file" name="file" id="file" onchange="upload()" style="display:none">
<div class="col-lg-6">
    <div id="cateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade text-left">
        <div role="document" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="exampleModalLabel" class="modal-title">
                        请选择导入文件的类型
                    </h4>
                </div>
                <div class="modal-body row">
                    <div class="form-horizontal">
                        <div class="row-fluid">
                            <label class="col-sm-2 control-label no-padding-right" style="margin-top:10px;"> 数据类型: </label>
                            <div class="col-sm-10">
                                <select name="cate" id="cate" class="form-control" style="width: 150px; margin-top:10px; margin-left:12px;">
                                    <?php foreach (\App\Models\Dao\SitesSource::$source_type_mapping as $k=> $v):?>
                                        <option value="<?=$k?>"><?=$v?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-secondary">关闭</button>
                    <button type="button" class="btn btn-info" onclick="change();">下一步</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-6">
    <div id="valueModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" class="modal fade text-left">
        <div role="document" class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="exampleModalLabel" class="modal-value"></h4>
                </div>
                <div class="modal-body row">
                    <div class="form-horizontal">
                        <input type="hidden" id="id" name="id" value="" />
                        <div class="row-fluid">
                            <label class="col-sm-2 control-label no-padding-right" style="margin-top:10px;"> 类型: </label>
                            <div class="col-sm-10">
                                <select name="cate" id="my_cate" class="form-control" style="width: 150px; margin-top:10px; margin-left:12px;">
                                    <?php foreach (\App\Models\Dao\SitesSource::$source_type_mapping as $k=> $v):?>
                                        <option value="<?=$k?>"><?=$v?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <label class="col-sm-2 control-label no-padding-right" style="margin-top:10px;"> 数据: </label>
                            <div class="col-sm-10">
                                <textarea  id="value" rows=6 name="value" class="col-sm-9" style="margin-top:10px; margin-left:12px;" placeholder="支持批量，换行分割"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-secondary">关闭</button>
                    <button type="button" class="btn btn-info" onclick="add();">保存</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('table th input:checkbox').on('click', function () {
        let that = this;
        $(this).closest('table').find('tr > td:first-child input:checkbox').each(function () {
            this.checked = that.checked;
            $(this).closest('tr').toggleClass('selected');
        });
    });
    function add() {
        let id = $("#id").val();
        let value = $("#value").val();
        let cate = $("#my_cate").val();
        $("#valueModal").modal("hide");
        $.ajax({
            url:'/source/sites',
            type:'post',
            data: {id:id, cate:cate, value:value},
            success:function(res){
                if(res.code !== 0){
                    layer.msg(res.message, {time:3000});
                }else{
                    layer.msg(res.message, {time:2000, end:function (){location.reload();}});
                }
            }
        })
    }
    $(".add").on("click", function(){
        clearModal($('.modal-body'));
        $(".modal-value").html('添加数据');
        $("#valueModal").modal("show");
    });

    $(".edit").on("click", function(){
        clearModal($('.modal-body'));
        $("#id").val($(this).attr('data-id'));
        $("#value").val($(this).attr('data-value'));
        $("#my_cate").val($(this).attr('data-cate'));
        $(".modal-value").html('编辑数据');
        $("#valueModal").modal("show");
    });

    $(".delete").on("click", function(){
        let id = $(this).attr('data-id');
        let title = $(this).attr('data-title');
        layer.confirm("你确认删除此数据: " + title + " 吗？", {icon: 3, title:'提示', btn:['确认','取消']}, function (){
            $.post('/source/deleteSiteData', {id:id}, function(res){
                if(res.code !== 0){
                    layer.msg(res.message, {time:3000});
                }else{
                    layer.msg(res.message, {time:2000, end:function (){location.reload();}});
                }
            });
        })
    })

    $(".batchDelete").on("click", function(){
        let ids = $("input:checkbox[name='id']:checked").map(function (index, ele) {
            return $(ele).val();
        }).get().join(",");
        if (!ids) {
            layer.msg("请选择需要操作的数据");
            return false;
        }
        let lid = ids.split(',').length;
        layer.confirm("你确认删除 " + lid + " 个数据吗？", {icon: 3, title:'提示', btn:['确认','取消']}, function (){
            $.post('/source/deleteSiteData', {id:ids}, function(res){
                if(res.code !== 0){
                    layer.msg(res.message, {time:3000});
                }else{
                    layer.msg(res.message, {time:2000, end:function (){location.reload();}});
                }
            });
        })
    });
    $(".upload").on('click', function() {
        $("#cateModal").modal("show");
    });
    function change(){
        $("#cateModal").modal("hide");
        $("#file").trigger("click");
    }
    function upload(){
        let formData = new FormData();
        formData.append('file', $('#file')[0].files[0]);
        formData.append('cate', $('#cate').val());
        $.ajax({
            url : '/source/sitesDataUpload',//这里写你的url
            type : 'POST',
            data : formData,
            contentType: false,// 当有文件要上传时，此项是必须的，否则后台无法识别文件流的起始位置
            processData: false,// 是否序列化data属性，默认true(注意：false时type必须是post)
            dataType: 'json',//这里是返回类型，一般是json,text等
            clearForm: true,//提交后是否清空表单数据
            success: function(res) { //提交成功后自动执行的处理函数，参数data就是服务器返回的数据。
                layer.msg(res.message, {time:2000, end:function (){location.reload();}});
            }
        });
    }
</script>